### ISSUE TITLE
TODO: setup

### ISSUE THREAD

**Issue by hjeongb0320** [hjeongb0320/nestjs-study#1]
[1차 기본 셋팅]
- [ ] 기초 파이프 구현
- [x] token 방식 로그인 구현
- [ ] session 방식 로그인 구현
- [ ] dev / prod config 나누기
- [ ] prod docker compose 관리하기
